### ISSUE TITLE
ComicPageType: Advertisement vs Advertisment

### ISSUE THREAD

**Issue by MichaelFitzurka** [anansi-project/comicinfo#19]
All of the schemas here have the page type listed as Advertisment <-- Without the 'e'.
But the original application saves the page type as Advertisement <-- With the 'e'.

This appears to be a bug that has carried through to even the 2.1 spec.

**Comment by gotson** [comment]
Hi, indeed it seems legit. Do you want to submit a PR ?

**Comment by MichaelFitzurka** [comment]
I will - to spec 1.0, 2.0 or 2.1 or all of the above?

**Comment by MichaelFitzurka** [comment]
Will do.
