### ISSUE TITLE
New element: Translator

### ISSUE THREAD

**Issue by gotson** [anansi-project/comicinfo#2]
# Where does this comes from?

The request came up via [Komga](https://github.com/gotson/komga/issues/740).

# What is the rationale for adding support for this element?

The existing schema already has various author roles, but Translator is not one of them. Translator could be used for both official translators, for instance for a Japanese manga published in France, and scanlators.

# Is the element already handled by any application or tool?

No.

**Comment by gotson** [comment]
Given the element is similar to existing roles, it seems right to use a similar schema, and allow multiple values separated by commas:

`<xs:element minOccurs="0" maxOccurs="1" default="" name="Translator" type="xs:string" />`

**Comment by majora2007** [comment]
Would the translator be the individual that performed the translation or the scene group that released the issue? 

For example, Scene group ColoredCouncil might release an issue, but the translations came from Viz (a company).

**Comment by majora2007** [comment]
What I'm saying is this:
ColoredCouncil does some sort of processing on files (they color them) and release them under their name. If you read up, they use Viz for the translations rather than fan translations. My question is, what would I expect to see in the field? Will it be Viz? Or would it be ColoredCouncil?

This is more about understanding for the tag writers than from a reading perspective.

**Comment by gotson** [comment]
> ColoredCouncil does some sort of processing on files (they color them)

Their name would probably fit better in the Colorist existing element then.

---

Totally understand your point. Part of the problem is there's no accepted way of filling the existing fields, partly because the format was never meant to be used outside ComicRack.

**Comment by gotson** [comment]
> Given the element is similar to existing roles, it seems right to use a similar schema, and allow multiple values separated by commas:
> 
> `<xs:element minOccurs="0" maxOccurs="1" default="" name="Translator" type="xs:string" />`

I'll cast my vote in favor of adding this field, similar to the other roles that already exist.  👍🏻

**Comment by majora2007** [comment]
I'm also fine with adding it, with comma separated.
