### ISSUE TITLE
AgeRating "MA 15+" should be "MA15+"

### ISSUE THREAD

**Issue by MichaelFitzurka** [anansi-project/comicinfo#21]
I hate being this guy ... but I am moving to 2.0 schema compliance and beyond.
The original Comic Rack application has the rating as "MA15+" (no space) vs "MA 15+" (with space).

**Comment by gotson** [comment]
Can you clarify what the issue is ? I don't exactly understand what you are saying.

**Comment by MichaelFitzurka** [comment]
The value in the ComicRack application does not have a space between the “MA” and the “18+” parts for this option in their Age Rating field.  That means comics created with this value from the ComicRack application would not pass a schema validation using the 2.0 and 2.1 schemas here.
