### ISSUE TITLE
StoryArcNumber with multiple story arcs

### ISSUE THREAD

**Issue by bpepple** [anansi-project/comicinfo#23]
I noticed StoryArcNumber was added in v2.1, and I'm not quite sure that handles issues with multiple story arcs very well. It might make more sense to make it complextype so each arc can have the arc number associated.

**Comment by gotson** [comment]
It's not documented, but values separated by comma will be handled in pair with the values in StoryArc.

It was added to handle this exact use case between Mylar and Komga.

**Comment by bpepple** [comment]
Figured it was a delimited string, but design-wise seems a bit fragile to do it this way. Might make sense to add a subelement or something to track the arc number with it's arc. Also, it might make it easier in the future you want to add anything else, like total arcs, etc

**Comment by gotson** [comment]
Keep it mind that we only do non breaking changes. It needs to remain compatible with the ComicRack usage too. So if people in CR wants to put multiple values, they would use comma separated, same as for authors.

The format has limitations, and the aim of this project is not to create a new format, just to make small mon breaking enhancements that are backward compatible.

It's not always pretty, but it works.

**Comment by gotson** [comment]
Resolved with https://github.com/anansi-project/anansi-project.github.io/commit/14588e3f481e860722a64e6e0160036347e781f2
