### ISSUE TITLE
New Element: Country

### ISSUE THREAD

**Issue by Dogway** [anansi-project/comicinfo#24]
# Where does this comes from?
Myself.

# What is the rationale for adding support for this element?
Know the country of the original comic publisher.

# Is the element already handled by any application or tool?
Haven't checked.

# Example
I saw 'Locations' which seems to describe where (city, country) the story arc sets. I don't see how this is relevant...

I also saw a 'Manga' entry, not sure what this is necessary for. Maybe we can have a 'Layout' entry instead to indicate if it's western read mode (Left to Right), manga read mode (Right to Left), or vertical. And another for view mode, single, double, triple (posters, etc) or continuous.

**Comment by majora2007** [comment]
This seems like a low effort post. You ask for a field, but give no rationale to what it's needed and no readers offer any support. Please update this ticket and re-open.

**Comment by Dogway** [comment]
The issue template asked for rationale to include the element, not rationale to what's needed. Let's not forget how to read.

Standards don't need to be used before they are created. More often than not it's the other way around.

I won't bother anymore on this, I'm creating my own universal book standard.

Good luck.

**Comment by majora2007** [comment]
I don't want to get into a flame war. My view was there was no rationale to what the new field would be for. If that's not present, then how would readers consume or this project document it. 

Best of luck on your book standard. I hope it gains traction over the limited nature of ComicInfo.
