### ISSUE TITLE
New Element: ISBN/Identifier

### ISSUE THREAD

**Issue by Rosalie241** [anansi-project/comicinfo#28]
## Where does this comes from?

Myself.

## What is the rationale for adding support for this element?

it'd be handy to know the ISBN number of the comic you're currently reading so you can more easily find it online, just like EPUB has the `identifier` element.

Both `ISBN` or `Identifier` would be fine with me, I'm not sure which one would make more sense naming-wise.

## Is the element already handled by any application or tool?

No, but I'd like to add support for it to [Librera Reader](https://github.com/foobnix/LibreraReader), to which I've already added basic support for ComicInfo.xml [here](https://github.com/foobnix/LibreraReader/pull/833).

**Comment by gotson** [comment]
Seems it's a subset of #12

**Comment by Rosalie241** [comment]
Hmm, seems about right, though it seems discussions didn't lead to much of a solution, so if I may, I'll propose one:

maybe have an `Identifier` element like this:
```
<Identifier type="ISBN">somenumber</Identifier>
```
where `type` can be i.e `ISBN` or others.

**Comment by gotson** [comment]
Solution come in a second stage, first there need to be some agreement that adding something makes sense.
