### ISSUE TITLE
Handling for Manga Volumes

### ISSUE THREAD

**Issue by SpiralCut** [anansi-project/comicinfo#32]
What is the expected data layout for manga volumes in comic info.xml? 

I see for western comics that volume corresponds to the year or subseries but this usage is significantly different from a manga Tankobon which is more like a western TPB except that they are expected for pretty much every series.

 Right now the only option seems to be to enter in Number but that is also used for Chapter number which can be confusing if you have both volumes and chapters for the same manga series.

**Comment by majora2007** [comment]
For manga volume you can fill out the Volume tag and when it comes to completion, both Komga and Kavita use Count to tell if it's complete or not.

The readers have their own logic for this. Kavita for example checks against chapters on disk and volumes and considers completion based on whichever matches.

**Comment by SpiralCut** [comment]
Thank you very much.  To confirm then, in the case of volume three of a four-volume completed manga with 32 chapters should have the following metadata:
Number: (blank)
Volume: 3
Count: 4

is that accurate?

**Comment by majora2007** [comment]
It depends on the reader for Publication status, but 100%, you should have `Volume 3`. For Kavita alone, I can say putting `Count 4` will treat the Series as Ended with 4 total volumes and 3/4 completed. I cannot speak to Komga. Unfortunately, the standard doesn't really have the needed field so each reader has it's own implementation. 

From my opinion, if I'm collecting Tankobon, which I prefer, then I don't care about how many total chapters there are.

**Comment by SpiralCut** [comment]
Ok, clear from my side. Thank you and I’ll go ahead and close the issue.
