### ISSUE TITLE
New element: Character design

### ISSUE THREAD

**Issue by bn-d** [anansi-project/comicinfo#34]
This might be manga specific. I don't think this fits any existing field (ie writer/penciller etc)

**Comment by gotson** [comment]
Please use the issue templates

**Comment by bn-d** [comment]
Where is the issue template?

**Comment by majora2007** [comment]
When you create the issue, it gives it to you in the description.

**Comment by bn-d** [comment]
![image](https://user-images.githubusercontent.com/10731263/199036427-abecbb9a-454a-43bd-9e21-d9adfcbc07f1.png)
It does not. The `.github/ISSUE_TEMPLATE` folder does not exist.

**Comment by majora2007** [comment]
Okay, well, please copy from another issue on here instead and recreate your issue. I can update so there is an issue template later.

**Comment by gotson** [comment]
@bn-d i am sorry about that, i really thought we did have that in place. I will add templates.
