### ISSUE TITLE
Missing tag : Tags

### ISSUE THREAD

**Issue by racine-p-a** [anansi-project/comicinfo#47]
Yesterday evening, I stumbled upon this thing : `Tags` are properly documented in [your documentation](https://anansi-project.github.io/fr/docs/comicinfo/documentation#tags) but are not present at all in [your .xsd file](https://github.com/anansi-project/comicinfo/blob/main/schema/v2.0/ComicInfo.xsd).
Is it a bug ? A regression ? A mistake ?

Sorry to bother you again with my dumb questions

**Comment by gotson** [comment]
https://github.com/anansi-project/comicinfo/blob/a54e86e2736e0910bc7f6413858d6e1eec9d049a/drafts/v2.1/ComicInfo.xsd#L30
