### ISSUE TITLE
New Element: Subtitle

### ISSUE THREAD

**Issue by ocgineer** [anansi-project/comicinfo#8]
### Where does this comes from?
Me

### What is the rationale for adding support for this element?
I noticed that there is no element to enter a subtitle of a book in case the book has it or to use it fine-tune titles.

For example, the one that came to mind to use it as, would be the 3 Fairy Tail "Side Story" manga's.
- Fairy Tail: Twin Dragons of Saber Tooth (1)
- Fairy Tail: Rhodonite (2)
- Fairy Tail: Lightning Gods (3)

One could set it up as;
- title: Fairy Tail Side Story 1
- subtitle: Twin Dragons of Saber Tooth

I do not know if there are more comics/manga with a potential subtitle but it could be handy for future cases.

**Comment by gotson** [comment]
This could be easily modelled with the soon-to-be-added `TitleSort` (see #4).

- Fairy Tail: Twin Dragons of Saber Tooth (1)
  - Title: Fairy Tail: Twin Dragons of Saber Tooth
  - TitleSort: Fairy Tail 1
- Fairy Tail: Rhodonite (2)
  - Title: Fairy Tail: Rhodonite
  - TitleSort: Fairy Tail 2
- Fairy Tail: Lightning Gods (3)
  - Title: Fairy Tail: Lightning Gods
  - TitleSort: Fairy Tail 3

I don't think there are any producing applications, and i don't see how the consuming applications would make use of this subtitle?

**Comment by majora2007** [comment]
I agree, I don't see where this would fit in for consuming applications and using Title or even AlternativeTitle.

**Comment by lordwelch** [comment]
Well if one is to go off of the current documentation already listed in the [repository/website](https://anansi-project.github.io/docs/comicinfo/documentation#alternateseries--alternatenumber--alternatecount) alternate series seems to describe this use-case.
Also what happens when there are multiple sub-titles? e.g. Batman: City of Crime: The Deluxe Edition

**Comment by gotson** [comment]
> Well if one is to go off of the current documentation already listed in the [repository/website](https://anansi-project.github.io/docs/comicinfo/documentation#alternateseries--alternatenumber--alternatecount) alternate series seems to describe this use-case. Also what happens when there are multiple sub-titles? e.g. Batman: City of Crime: The Deluxe Edition

Actually `AlternateSeries` is mostly used for crossovers or story arcs.

**Comment by gotson** [comment]
maybe we need to clarify something, is this about a book subtitle, or a series subtitle ?

My assumption was that it was about a series, but it seems you indicate that this is about a book.

**Comment by ocgineer** [comment]
Subtitle of a single book.

Like in my example, the series would be: **Fairy Tail Side Story** and the book subtitle of v1 would be **Twin Dragons of Saber Tooth**.

**Comment by gotson** [comment]
I don't understand.

If the book has a title, why not have the title of the book be `Twin Dragons of Saber Tooth` instead of `Fairy Tail Side Story Vol. 1`. The book also has a `Number`, which in this case would be `1` i assume.

**Comment by gotson** [comment]
Closing this as there is no real clear requirement.
